### ISSUE TITLE
寻找quad标签顶点那里有点不理解，

### ISSUE THREAD

**Issue by ArchCodeEmbodyRomance** [akof1314/uGUI_LinkImageText#2]
protected void UpdateQuadImage()
    {
        ....
        foreach (Match match in s_ImageRegex.Matches(m_OutputText))
        {
            var picIndex = match.Index;
            var endIndex = picIndex * 4 + 3;
            m_ImagesVertexIndex.Add(endIndex);

在quad标签的位置只会生成一个面片，这样的话虽然标签有很多字，但是只有4个顶点，所以会造成顶点位置并不一定等于标签位置*4，但是程序中是用标签位置*4。

这里不是很明白，希望您能帮我解答一下，非常感谢。

**Comment by akof1314** [comment]
这段话不是在我的文章中呀

**Comment by ArchCodeEmbodyRomance** [comment]
不好意思，我没说清楚，那段话是我看源码的理解。
在我标识的代码上，查找文字起始顶点是通过文字位置乘4。
但是在我的理解中，<quad/>标签里虽然有很多字但是只生成了4个顶点，所以感觉在求第二个<quad/>的时候应该减去match.length +1再乘4 才应该是正确的顺序。
这里感觉有点别扭。

**Comment by akof1314** [comment]
没关系，只要能找到正确的顶点就行

**Comment by ArchCodeEmbodyRomance** [comment]
哦哦，谢谢您
